version: "3.9"
services:
  backend:
    image: golatex-backend # Use the existing image
    container_name: golatex-backend-container
    ports:
      - "8080:8080"
    volumes:
      - ./doclean-backend:/app
      - /app/tmp
    command: ["air", "-c", ".air.toml"]
  frontend:
    image: golatex-frontend
    container_name: golatex-frontend-container
    ports:
      - "3006:3006"
    volumes:
      - ./doclean-frontend:/app
      - ./doclean-frontend/node_modules:/app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: npm run dev
